name: Build and Deploy Java Application

on:
  push:
    branches:
      - main # Укажите нужную ветку, например, "main" или "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 45.141.103.51 >> ~/.ssh/known_hosts
          scp target/Telegram-bot.jar root@45.141.103.51: /usr/bin/tg_bot/
          ssh root@45.141.103.51 'java -jar  /usr/bin/tg_bot/Telegram-bot.jar'
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
